/**
 * Shared bilingual string tables (en + zh-TW) for the opencode-panel UI.
 *
 * `STRING_IDS` enumerates every user-facing string id the webview (and any
 * host-side surface consuming the same tables) may render. `en` and `zhTW`
 * are typed `Record<StringId, string>`, so the TypeScript compiler proves at
 * build time that BOTH tables carry exactly the same ids — a missing key in
 * either table (or an id in a table that is not in the union) is a compile
 * error. Runtime drift beyond the compiler's reach is guarded by
 * scripts/check-i18n.mjs (table parity) and src/shared/__tests__/strings.test.ts.
 *
 * This module is intentionally self-contained (no imports): scripts/check-i18n.mjs
 * loads it through esbuild + a data: URL so the parity check needs no build step.
 */
// allow: SIZE_OK — pure bilingual data tables (636 ids x 2 locales); a single
// authority file is the todo-4 spec and keeps diff-per-locale review sane.

export const STRING_IDS = [
  // app shell
  "app.loading",
  "app.name",
  // slash-command palette
  "commands.empty",
  "commands.title",
  // composer
  "composer.abort",
  "composer.draftRestored",
  "composer.autoMode.off",
  "composer.cancel",
  "composer.autoMode.on",
  "composer.autoMode.title",
  "composer.effort.none",
  "composer.effort.title",
  "composer.variant.fast",
  "composer.variant.high",
  "composer.variant.low",
  "composer.variant.max",
  "composer.variant.medium",
  "composer.variant.off",
  "composer.variant.on",
  "composer.variant.thinking",
  "composer.optionsMenu",
  "composer.openSettings",
  "composer.placeholder",
  "composer.queued",
  "composer.send",
  // shared chrome
  "common.cancel",
  "common.close",
  "common.confirm",
  // capability-driven degradation
  "capability.hidden",
  // context/token usage strip
  "chat.usage",
  "chat.usage.input",
  "chat.usage.output",
  "chat.usage.reasoning",
  // todos/diffs dock
  "dock.diffs.empty",
  "dock.diffs.fileLink",
  "dock.diffs.openDiff",
  "dock.diffs.openFile",
  "dock.diffs.openUnavailable",
  "dock.diffs.title",
  "dock.todos.empty",
  "dock.todos.title",
  // error boundary
  "error.boundary.title",
  // header overflow menu
  "menu.more",
  "menu.openTui",
  "mention.count",
  "mention.paletteHint",
  // MCP status panel
  "mcp.nativeOnly",
  "mcp.omoNote",
  "mcp.title",
  // message list
  "chat.jumpBack",
  "chat.scrollBottom",
  "chat.systemReminder.label",
  "messages.collapseTool",
  "messages.empty",
  "messages.expandTool",
  "messages.export",
  "messages.regenerate",
  "messages.revert",
  "messages.revertConfirm",
  "messages.shell",
  "messages.shellPlaceholder",
  "messages.summarize",
  "messages.thinking",
  "messages.unrevert",
  // permission approval cards
  "permission.allowAlways",
  "permission.allowOnce",
  "permission.approvedState",
  "permission.expired",
  "permission.reject",
  "permission.title",
  // agent/model pickers
  "picker.agent.customBadge",
  "picker.agent.customPickedToast",
  "picker.agent.lockedToast",
  "picker.agent.title",
  "picker.model.lockedReason",
  "picker.model.lockedToast",
  "picker.model.pickedWarningToast",
  "picker.model.title",
  // question.asked cards
  "question.answerPlaceholder",
  "question.completed",
  "question.customPlaceholder",
  "question.selectedPrefix",
  "question.submit",
  "question.title",
  "question.unavailable",
  // server lifecycle status
  "server.oldVersion",
  "server.status.attached",
  "server.status.connected",
  "server.status.lost",
  "server.status.managed",
  "server.status.probing",
  "server.status.retry",
  "server.status.stopped",
  // sessions panel
  "sessions.closeHistory",
  "sessions.compress",
  "sessions.delete",
  "sessions.deleteConfirm",
  "sessions.empty",
  "sessions.fork",
  "sessions.history",
  "sessions.historyTitle",
  "sessions.new",
  "sessions.rename",
  "sessions.renamePrompt",
  "sessions.searchPlaceholder",
  "sessions.share",
  "sessions.shareCopied",
  "sessions.title",
  "sessions.unshare",
  "sessions.viewAll",
  // settings page
  "settings.apply",
  "settings.connectionFailed",
  "settings.compress",
  "settings.connectionOk",
  "settings.enumOption.auto",
  "settings.enumOption.en",
  "settings.enumOption.zhTW",
  "settings.field.autoStartServer",
  "settings.field.binaryPath",
  "settings.field.chatFontFamily",
  "settings.field.chatFontSize",
  "settings.field.debugLogs",
  "settings.field.hostname",
  "settings.field.language",
  "settings.field.minimumServerVersion",
  "settings.field.port",
  "settings.field.serverArgs",
  "settings.field.serverPassword",
  "settings.field.serverUrl",
  "settings.field.serverUsername",
  "settings.placeholder",
  "settings.revert",
  "settings.saveFailed",
  "settings.saved",
  "settings.section.appearance",
  "settings.section.capabilities",
  "settings.section.diagnostics",
  "settings.section.server",
  "settings.scope.user",
  "settings.scope.workspace",
  "settings.secret.clear",
  "settings.secret.isSet",
  "settings.secret.notSet",
  "settings.serverActionsHint",
  "settings.testConnection",
  "settings.title",
  "settings.validationFailed",
  // generic tool-call card status chips
  "tool.status.completed",
  "tool.status.failed",
  "tool.copiedState",
  "tool.copyLabel",
  "tool.output.collapse",
  "tool.output.expand",
  "tool.searchPrefix",
  "tool.searchQuery",
  "tool.backgroundTask",
  "tool.omittedLinesSuffix",
  "subagent.completedNote",
  "subagent.fallbackTaskLabel",
  "subagent.liveIndicator",
  "subagent.logStepsLabel",
  "subagent.runningInBackground",
  "subagent.statusFinished",
  "subagent.statusRunning",
  "subagent.taskDescriptionLabel",
  "tool.status.pending",
  "tool.status.running",
  "welcome.explain",
  "welcome.explainDesc",
  "welcome.findBugs",
  "welcome.findBugsDesc",
  "welcome.refactor",
  "welcome.refactorDesc",
  "welcome.title",
  "welcome.unitTests",
  "welcome.unitTestsDesc",
  // config-file editor — tabs, scopes, file states, actions, notices
  "cfg.tab.general",
  "cfg.tab.opencode",
  "cfg.tab.omo",
  "cfg.scope.global",
  "cfg.scope.project",
  "cfg.file.path",
  "cfg.file.missing",
  "cfg.file.create",
  "cfg.file.parseError",
  "cfg.file.readOnly",
  "cfg.file.saved",
  "cfg.file.conflict",
  "cfg.action.reload",
  "cfg.action.force",
  "cfg.notice.deprecated",
  "cfg.notice.unknown",
  "cfg.notice.legacy",
  "cfg.notice.profiles",
  "cfg.notice.sharedBase",
  "cfg.notice.noWorkspace",
  "cfg.advanced.title",
  "cfg.records.add",
  "cfg.records.remove",
  "cfg.kv.add",
  "cfg.kv.key",
  "cfg.kv.value",
  "cfg.list.add",
  "cfg.masked.set",
  "cfg.masked.clear",
  "cfg.masked.isSet",
  "cfg.preview.title",
  // config editor sections — opencode tab
  "cfg.sec.oc.general",
  "cfg.sec.oc.plugins",
  "cfg.sec.oc.permission",
  "cfg.sec.oc.agents",
  "cfg.sec.oc.mcp",
  "cfg.sec.oc.providers",
  "cfg.sec.oc.runtime",
  "cfg.sec.oc.server",
  "cfg.sec.oc.commands",
  "cfg.sec.oc.formatter",
  "cfg.sec.oc.lsp",
  "cfg.sec.oc.watcher",
  "cfg.sec.oc.tools",
  "cfg.sec.oc.compaction",
  "cfg.sec.oc.attachment",
  "cfg.sec.oc.experimental",
  "cfg.sec.oc.enterprise",
  "cfg.sec.oc.skills",
  "cfg.sec.oc.references",
  "cfg.sec.oc.schema",
  // config editor sections — omo tab
  "cfg.sec.omo.agents",
  "cfg.sec.omo.categories",
  "cfg.sec.omo.disabled",
  "cfg.sec.omo.backgroundTask",
  "cfg.sec.omo.sisyphus",
  "cfg.sec.omo.memory",
  "cfg.sec.omo.runtimeFallback",
  "cfg.sec.omo.modelCapabilities",
  "cfg.sec.omo.tmux",
  "cfg.sec.omo.gitMaster",
  "cfg.sec.omo.browserAutomation",
  "cfg.sec.omo.codegraph",
  "cfg.sec.omo.claudeCode",
  "cfg.sec.omo.integrations",
  "cfg.sec.omo.experimental",
  "cfg.sec.omo.other",
  "cfg.sec.omo.shared",
  // config editor field labels — one id per unique key segment across the
  // opencode.json + omo.jsonc inventories (cfg.f.<segmentLowerCamel>)
  "cfg.f.action",
  "cfg.f.agent",
  "cfg.f.agentDefinitions",
  "cfg.f.agentOrder",
  "cfg.f.agentPaneMinWidth",
  "cfg.f.agents",
  "cfg.f.aggressive",
  "cfg.f.aggressiveTruncation",
  "cfg.f.allowedCommands",
  "cfg.f.allowedSubagents",
  "cfg.f.allowedTools",
  "cfg.f.allowNonGptModel",
  "cfg.f.anthropicProvider",
  "cfg.f.api",
  "cfg.f.apiKey",
  "cfg.f.argumentHint",
  "cfg.f.attachment",
  "cfg.f.authorizedDiscordUserIds",
  "cfg.f.auto",
  "cfg.f.autoCommit",
  "cfg.f.autoInit",
  "cfg.f.autoProvision",
  "cfg.f.autoRefreshOnStart",
  "cfg.f.autoResize",
  "cfg.f.autoSelectMax",
  "cfg.f.autoSelectMaxChars",
  "cfg.f.autoshare",
  "cfg.f.autoStart",
  "cfg.f.autoUpdate",
  "cfg.f.autoupdate",
  "cfg.f.babysitting",
  "cfg.f.backendType",
  "cfg.f.background",
  "cfg.f.backgroundTask",
  "cfg.f.baseDir",
  "cfg.f.baseURL",
  "cfg.f.bash",
  "cfg.f.batchMaxBytes",
  "cfg.f.batchMaxLines",
  "cfg.f.batchTool",
  "cfg.f.blacklist",
  "cfg.f.branch",
  "cfg.f.browserAutomationEngine",
  "cfg.f.budgetTokens",
  "cfg.f.cacheRead",
  "cfg.f.cacheWrite",
  "cfg.f.callbackPort",
  "cfg.f.categories",
  "cfg.f.category",
  "cfg.f.chunkTimeout",
  "cfg.f.circuitBreaker",
  "cfg.f.claudeCode",
  "cfg.f.claudeCodeCompat",
  "cfg.f.clientId",
  "cfg.f.clientSecret",
  "cfg.f.codegraph",
  "cfg.f.color",
  "cfg.f.command",
  "cfg.f.commands",
  "cfg.f.commentChecker",
  "cfg.f.commitFooter",
  "cfg.f.compaction",
  "cfg.f.compatibility",
  "cfg.f.compileWarnTokens",
  "cfg.f.consecutiveThreshold",
  "cfg.f.context",
  "cfg.f.contextOver200k",
  "cfg.f.continueLoopOnDeny",
  "cfg.f.cooldownSeconds",
  "cfg.f.cors",
  "cfg.f.cost",
  "cfg.f.createdAt",
  "cfg.f.customPrompt",
  "cfg.f.cwd",
  "cfg.f.daemon",
  "cfg.f.dag",
  "cfg.f.debounceSettles",
  "cfg.f.deduplication",
  "cfg.f.defaultAgent",
  "cfg.f.defaultBuilderEnabled",
  "cfg.f.defaultConcurrency",
  "cfg.f.defaultExecutionMode",
  "cfg.f.defaultMaxIterations",
  "cfg.f.defaultMode",
  "cfg.f.defaultMs",
  "cfg.f.defaultRunAgent",
  "cfg.f.description",
  "cfg.f.disable",
  "cfg.f.disabled",
  "cfg.f.disabledAgents",
  "cfg.f.disabledCommands",
  "cfg.f.disabledHooks",
  "cfg.f.disabledKeywords",
  "cfg.f.disabledMcps",
  "cfg.f.disabledProviders",
  "cfg.f.disabledSkills",
  "cfg.f.disabledTools",
  "cfg.f.disableLiveParentWakeRouting",
  "cfg.f.disableOmoEnv",
  "cfg.f.disablePasteSummary",
  "cfg.f.disallowedTools",
  "cfg.f.discordBotToken",
  "cfg.f.discordChannelId",
  "cfg.f.discordMention",
  "cfg.f.displayName",
  "cfg.f.doomLoop",
  "cfg.f.dream",
  "cfg.f.dynamicContextPruning",
  "cfg.f.edit",
  "cfg.f.editNotice",
  "cfg.f.effect",
  "cfg.f.enable",
  "cfg.f.enabled",
  "cfg.f.enabledExpansions",
  "cfg.f.enabledProviders",
  "cfg.f.enterprise",
  "cfg.f.enterpriseUrl",
  "cfg.f.env",
  "cfg.f.environment",
  "cfg.f.everyUserTurns",
  "cfg.f.excludedRoots",
  "cfg.f.executionMode",
  "cfg.f.experimental",
  "cfg.f.extensions",
  "cfg.f.externalDirectory",
  "cfg.f.facts",
  "cfg.f.fallbackModels",
  "cfg.f.family",
  "cfg.f.field",
  "cfg.f.forceEnable",
  "cfg.f.formatter",
  "cfg.f.from",
  "cfg.f.gateway",
  "cfg.f.gateways",
  "cfg.f.gitEnvPrefix",
  "cfg.f.gitMaster",
  "cfg.f.glob",
  "cfg.f.goal",
  "cfg.f.grep",
  "cfg.f.hashlineEdit",
  "cfg.f.headers",
  "cfg.f.headerTimeout",
  "cfg.f.heartbeatMs",
  "cfg.f.hidden",
  "cfg.f.historyDefaultLimit",
  "cfg.f.historyMaxLimit",
  "cfg.f.hooks",
  "cfg.f.hostname",
  "cfg.f.i18n",
  "cfg.f.id",
  "cfg.f.idleMinutes",
  "cfg.f.ignore",
  "cfg.f.image",
  "cfg.f.includeCoAuthoredBy",
  "cfg.f.includePrefix",
  "cfg.f.initialization",
  "cfg.f.input",
  "cfg.f.installDir",
  "cfg.f.instruction",
  "cfg.f.instructions",
  "cfg.f.interleaved",
  "cfg.f.isActive",
  "cfg.f.isolation",
  "cfg.f.isUnstableAgent",
  "cfg.f.keywordDetector",
  "cfg.f.kind",
  "cfg.f.layout",
  "cfg.f.leadAgentId",
  "cfg.f.legacyMigrations",
  "cfg.f.license",
  "cfg.f.limit",
  "cfg.f.lineMaxBytes",
  "cfg.f.list",
  "cfg.f.liveModeEnabled",
  "cfg.f.locale",
  "cfg.f.logLevel",
  "cfg.f.lsp",
  "cfg.f.mailboxPollIntervalMs",
  "cfg.f.mainPaneMinWidth",
  "cfg.f.mainPaneSize",
  "cfg.f.maxBase64Bytes",
  "cfg.f.maxBytes",
  "cfg.f.maxDepth",
  "cfg.f.maxEntries",
  "cfg.f.maxEntryChars",
  "cfg.f.maxFallbackAttempts",
  "cfg.f.maxHeight",
  "cfg.f.maxLines",
  "cfg.f.maxMembers",
  "cfg.f.maxMemberTurns",
  "cfg.f.maxMessageLength",
  "cfg.f.maxMessagesPerRun",
  "cfg.f.maxMonitorsPerSession",
  "cfg.f.maxMs",
  "cfg.f.maxNodesPerRun",
  "cfg.f.maxParallelMembers",
  "cfg.f.maxPromptBytes",
  "cfg.f.maxPromptTokens",
  "cfg.f.maxRunsPerSession",
  "cfg.f.maxRuntimeMs",
  "cfg.f.maxSteps",
  "cfg.f.maxTokens",
  "cfg.f.maxToolCalls",
  "cfg.f.maxTools",
  "cfg.f.maxTurns",
  "cfg.f.maxWallClockMinutes",
  "cfg.f.maxWidth",
  "cfg.f.mcp",
  "cfg.f.mcpEnvAllowlist",
  "cfg.f.mcpTimeout",
  "cfg.f.mdns",
  "cfg.f.mdnsDomain",
  "cfg.f.members",
  "cfg.f.memory",
  "cfg.f.merge",
  "cfg.f.messagePayloadMaxBytes",
  "cfg.f.messageStalenessTimeoutMs",
  "cfg.f.metadata",
  "cfg.f.method",
  "cfg.f.migrations",
  "cfg.f.minHoursBetween",
  "cfg.f.minMs",
  "cfg.f.modalities",
  "cfg.f.mode",
  "cfg.f.model",
  "cfg.f.modelCapabilities",
  "cfg.f.modelConcurrency",
  "cfg.f.modelFallback",
  "cfg.f.modelFallbackTitle",
  "cfg.f.models",
  "cfg.f.monitor",
  "cfg.f.name",
  "cfg.f.newTaskSystemEnabled",
  "cfg.f.notification",
  "cfg.f.notifyOnFallback",
  "cfg.f.npm",
  "cfg.f.nudge",
  "cfg.f.oauth",
  "cfg.f.onCompaction",
  "cfg.f.openclaw",
  "cfg.f.openTelemetry",
  "cfg.f.options",
  "cfg.f.output",
  "cfg.f.path",
  "cfg.f.paths",
  "cfg.f.pattern",
  "cfg.f.patternMaxLength",
  "cfg.f.people",
  "cfg.f.permission",
  "cfg.f.permissionDefault",
  "cfg.f.plannerEnabled",
  "cfg.f.playwrightMcpArgs",
  "cfg.f.plugin",
  "cfg.f.pluginLoadTimeoutMs",
  "cfg.f.plugins",
  "cfg.f.pluginsOverride",
  "cfg.f.policies",
  "cfg.f.pollIntervalMs",
  "cfg.f.port",
  "cfg.f.preemptiveCompaction",
  "cfg.f.preserveRecentTokens",
  "cfg.f.primaryTools",
  "cfg.f.profiles",
  "cfg.f.prompt",
  "cfg.f.promptAppend",
  "cfg.f.protectedTools",
  "cfg.f.provider",
  "cfg.f.providerConcurrency",
  "cfg.f.providerOptions",
  "cfg.f.prune",
  "cfg.f.purgeErrors",
  "cfg.f.question",
  "cfg.f.ralphLoop",
  "cfg.f.rateLimitPerMinute",
  "cfg.f.read",
  "cfg.f.reasoning",
  "cfg.f.reasoningEffort",
  "cfg.f.reattachOnReconcile",
  "cfg.f.recipientUnreadMaxBytes",
  "cfg.f.recursive",
  "cfg.f.redirectUri",
  "cfg.f.reference",
  "cfg.f.references",
  "cfg.f.reflection",
  "cfg.f.refreshTimeoutMs",
  "cfg.f.releaseDate",
  "cfg.f.remote",
  "cfg.f.replacePlan",
  "cfg.f.replyListener",
  "cfg.f.repository",
  "cfg.f.reserved",
  "cfg.f.residencyMaxChildren",
  "cfg.f.resource",
  "cfg.f.restorePrimaryAfterCooldown",
  "cfg.f.resumeChildren",
  "cfg.f.retentionDays",
  "cfg.f.retryOnErrors",
  "cfg.f.ringMaxLines",
  "cfg.f.runtimeFallback",
  "cfg.f.safeHookCreation",
  "cfg.f.sandbox",
  "cfg.f.schema",
  "cfg.f.scope",
  "cfg.f.search",
  "cfg.f.server",
  "cfg.f.sessionGoneTimeoutMs",
  "cfg.f.sessionPermission",
  "cfg.f.sessionStartCooldownMs",
  "cfg.f.setCacheKey",
  "cfg.f.share",
  "cfg.f.shell",
  "cfg.f.shutdownLaunch",
  "cfg.f.sidebar",
  "cfg.f.sisyphus",
  "cfg.f.sisyphusAgent",
  "cfg.f.skill",
  "cfg.f.skills",
  "cfg.f.smallModel",
  "cfg.f.snapshot",
  "cfg.f.soul",
  "cfg.f.sourceUrl",
  "cfg.f.sources",
  "cfg.f.staleTimeoutMs",
  "cfg.f.startWork",
  "cfg.f.stateDir",
  "cfg.f.status",
  "cfg.f.stepCount",
  "cfg.f.steps",
  "cfg.f.storagePath",
  "cfg.f.strategies",
  "cfg.f.subagentDepth",
  "cfg.f.subagentType",
  "cfg.f.subscriberRing",
  "cfg.f.subscriptions",
  "cfg.f.subtask",
  "cfg.f.supersedeWrites",
  "cfg.f.sync",
  "cfg.f.syncPollTimeoutMs",
  "cfg.f.tailTurns",
  "cfg.f.task",
  "cfg.f.taskCleanupDelayMs",
  "cfg.f.taskListId",
  "cfg.f.tasks",
  "cfg.f.taskSystem",
  "cfg.f.taskTtlMs",
  "cfg.f.tdd",
  "cfg.f.team",
  "cfg.f.teamAllowedPaths",
  "cfg.f.teamMode",
  "cfg.f.telegramBotToken",
  "cfg.f.telegramChatId",
  "cfg.f.telemetry",
  "cfg.f.temperature",
  "cfg.f.template",
  "cfg.f.textVerbosity",
  "cfg.f.thinking",
  "cfg.f.timeout",
  "cfg.f.timeoutMinutes",
  "cfg.f.timeoutMs",
  "cfg.f.timeoutSeconds",
  "cfg.f.tmux",
  "cfg.f.tmuxVisualization",
  "cfg.f.todowrite",
  "cfg.f.toolCall",
  "cfg.f.toolExposure",
  "cfg.f.toolOutput",
  "cfg.f.tools",
  "cfg.f.topP",
  "cfg.f.trigger",
  "cfg.f.truncateAllToolOutputs",
  "cfg.f.ttlMs",
  "cfg.f.tui",
  "cfg.f.turnProtection",
  "cfg.f.turns",
  "cfg.f.type",
  "cfg.f.ultrawork",
  "cfg.f.unavailableCategories",
  "cfg.f.url",
  "cfg.f.urls",
  "cfg.f.username",
  "cfg.f.variant",
  "cfg.f.variants",
  "cfg.f.version",
  "cfg.f.wait",
  "cfg.f.warnings",
  "cfg.f.warnUnavailable",
  "cfg.f.watchDebounceMs",
  "cfg.f.watcher",
  "cfg.f.webfetch",
  "cfg.f.websearch",
  "cfg.f.whitelist",
  "cfg.f.worktreePath",
  "cfg.f.writeNotice",
] as const;

export type StringId = (typeof STRING_IDS)[number];

/** Locales with a complete string table. Host maps vscode.env.language onto these. */
export const SUPPORTED_LOCALES = ["en", "zh-TW"] as const;
export type SupportedLocale = (typeof SUPPORTED_LOCALES)[number];

export const en: Record<StringId, string> = {
  "app.loading": "Loading…",
  "app.name": "OpenCode Panel",
  "commands.empty": "No matching commands",
  "commands.title": "Commands",
  "composer.abort": "Stop generating",
  "composer.draftRestored": "Unsent draft restored",
  "composer.autoMode.off": "OFF",
  "composer.autoMode.on": "ON",
  "composer.autoMode.title": "Auto mode (auto-run all tool calls)",
  "composer.cancel": "Cancel",
  "composer.effort.none": "This model has no reasoning-effort settings",
  "composer.effort.title": "Effort (thinking effort)",
  "composer.variant.fast": "Fast (no thinking)",
  "composer.variant.high": "High (deep thinking)",
  "composer.variant.low": "Low (quick thinking)",
  "composer.variant.max": "Max (full thinking)",
  "composer.variant.medium": "Medium (standard thinking)",
  "composer.variant.off": "Off (no thinking)",
  "composer.variant.on": "On (enable thinking)",
  "composer.variant.thinking": "Thinking (enable thinking)",
  "composer.optionsMenu": "Options menu",
  "composer.openSettings": "Open Settings...",
  "composer.placeholder": "Ask opencode anything...",
  "composer.queued": "Queued: {text}",
  "composer.send": "Send",
  "common.cancel": "Cancel",
  "common.close": "Close",
  "common.confirm": "Confirm",
  "capability.hidden": "This feature is not supported by the connected server",
  "chat.usage": "Session token usage",
  "chat.usage.input": "in",
  "chat.usage.output": "out",
  "chat.usage.reasoning": "reasoning",
  "dock.diffs.empty": "No file changes in this session",
  "dock.diffs.fileLink": "File ↗",
  "dock.diffs.openDiff": "Open diff",
  "dock.diffs.openFile": "Open file",
  "dock.diffs.openUnavailable": "Cannot open the diff: the session is unknown",
  "dock.diffs.title": "File changes",
  "dock.todos.empty": "No todos yet",
  "dock.todos.title": "Todos",
  "error.boundary.title": "Something went wrong",
  "menu.more": "More actions",
  "menu.openTui": "Open TUI",
  "mention.count": "{count} items",
  "mention.paletteHint": "Mention files or symbols",
  "mcp.nativeOnly": "Natively configured MCP servers only",
  "mcp.omoNote": "oh-my-opencode detected: plugins may inject additional MCPs not listed here.",
  "mcp.title": "MCP servers",
  "chat.jumpBack": "Jump back to this prompt",
  "chat.scrollBottom": "Scroll to the newest message",
  "chat.systemReminder.label": "System reminder · Background task notice",
  "messages.collapseTool": "Collapse tool call details",
  "messages.empty": "No messages yet — send a prompt to begin.",
  "messages.expandTool": "Expand tool call details",
  "messages.export": "Export transcript",
  "messages.regenerate": "Regenerate",
  "messages.revert": "Revert to here",
  "messages.revertConfirm": "Revert the session to this message? File changes made after this point will be undone.",
  "messages.shell": "Run shell command",
  "messages.shellPlaceholder": "e.g. git status",
  "messages.summarize": "Summarize / compact session",
  "messages.thinking": "Thinking",
  "messages.unrevert": "Restore reverted messages",
  "permission.allowAlways": "Always allow",
  "permission.allowOnce": "Allow once",
  "permission.approvedState": "Approved",
  "permission.expired": "This permission request has expired",
  "permission.reject": "Reject",
  "permission.title": "Permission required",
  "picker.agent.customBadge": "custom",
  "picker.agent.customPickedToast": 'Custom agent "{name}" picked.',
  "picker.agent.lockedToast": 'Agent "{name}" is locked to dedicated model "{model}".',
  "picker.agent.title": "Select agent",
  "picker.model.lockedReason": '🔒 Agent "{name}" is locked to dedicated model "{model}"; manual switch disabled.',
  "picker.model.lockedToast": 'Agent "{name}" is bound to dedicated model "{model}". For free model selection, use a general-purpose agent (build / general).',
  "picker.model.pickedWarningToast": 'Model set to "{model}". If the active custom agent "{name}" has a dedicated model, it takes precedence on the backend. For fully manual model choice, use the build / general agent.',
  "picker.model.title": "Select model",
  "question.answerPlaceholder": "Type your answer...",
  "question.completed": "Completed",
  "question.customPlaceholder": "Other notes (optional)...",
  "question.selectedPrefix": "Selected:",
  "question.submit": "Submit answer",
  "question.title": "opencode is asking a question",
  "question.unavailable": "The connected server does not support answering questions from the panel.",
  "server.oldVersion": "The connected server is below the recommended version; some features are hidden.",
  "server.status.attached": "Server running (attached)",
  "server.status.connected": "Server connected",
  "server.status.lost": "Connection to the opencode server was lost",
  "server.status.managed": "Server running (managed by this extension)",
  "server.status.probing": "Connecting to server…",
  "server.status.retry": "Retry",
  "server.status.stopped": "Server stopped",
  "sessions.closeHistory": "Close session history",
  "sessions.compress": "Compact",
  "sessions.delete": "Delete",
  "sessions.deleteConfirm": "Delete this session? This cannot be undone.",
  "sessions.empty": "No sessions yet — create one to start chatting.",
  "sessions.fork": "Fork",
  "sessions.history": "History",
  "sessions.historyTitle": "Session history",
  "sessions.new": "New Session",
  "sessions.rename": "Rename",
  "sessions.renamePrompt": "Enter a new session title",
  "sessions.searchPlaceholder": "Search sessions…",
  "sessions.share": "Share",
  "sessions.shareCopied": "Share link copied to clipboard",
  "sessions.title": "Sessions",
  "sessions.unshare": "Stop sharing",
  "sessions.viewAll": "View all ({count})",
  "settings.apply": "Apply",
  "settings.compress": "Compact",
  "settings.connectionFailed": "Connection failed",
  "settings.connectionOk": "Connection succeeded",
  "settings.enumOption.auto": "Auto (follow VS Code)",
  "settings.enumOption.en": "English",
  "settings.enumOption.zhTW": "繁體中文",
  "settings.field.autoStartServer": "Auto-start server",
  "settings.field.binaryPath": "opencode binary path",
  "settings.field.chatFontFamily": "Chat font family",
  "settings.field.chatFontSize": "Chat font size",
  "settings.field.debugLogs": "Debug logs",
  "settings.field.hostname": "Hostname",
  "settings.field.language": "Interface language",
  "settings.field.minimumServerVersion": "Minimum server version",
  "settings.field.port": "Port",
  "settings.field.serverArgs": "Server startup arguments",
  "settings.field.serverPassword": "Server password",
  "settings.field.serverUrl": "Server URL",
  "settings.field.serverUsername": "Server username (optional)",
  "settings.placeholder": "Nothing to configure here yet.",
  "settings.revert": "Revert",
  "settings.saveFailed": "Failed to save settings",
  "settings.saved": "Settings saved",
  "settings.section.appearance": "Appearance",
  "settings.section.capabilities": "Capabilities",
  "settings.section.diagnostics": "Diagnostics",
  "settings.section.server": "Server",
  "settings.scope.user": "User",
  "settings.scope.workspace": "Workspace",
  "settings.secret.clear": "Clear",
  "settings.secret.isSet": "Saved",
  "settings.secret.notSet": "Not set",
  "settings.serverActionsHint": "Use the command palette to start, stop, or restart the server.",
  "settings.testConnection": "Test connection",
  "settings.title": "Settings",
  "settings.validationFailed": "Invalid value",
  "tool.copiedState": "Copied ✓",
  "tool.copyLabel": "Copy",
  "tool.searchPrefix": "Search:",
  "tool.searchQuery": "Search: {query}",
  "tool.backgroundTask": "Background task ({taskId})",
  "tool.omittedLinesSuffix": "... (+{count} lines omitted)",
  "subagent.completedNote": "✓ Subagent finished the task.",
  "subagent.fallbackTaskLabel": "Task: {title}",
  "subagent.liveIndicator": "Live",
  "subagent.logStepsLabel": "Steps (Subagent Logs)",
  "subagent.runningInBackground": "Subagent is computing in background, working on the task...",
  "subagent.statusFinished": "Call finished",
  "subagent.statusRunning": "Running...",
  "subagent.taskDescriptionLabel": "Task description",
  "tool.status.completed": "Completed",
  "tool.status.failed": "Failed",
  "tool.output.collapse": "Show less",
  "tool.output.expand": "Show more (+{count} lines)",
  "tool.status.pending": "Pending",
  "tool.status.running": "Running",
  "welcome.explain": "Explain Code",
  "welcome.explainDesc": "Analyze selected logic or the active file",
  "welcome.findBugs": "Find Bugs",
  "welcome.findBugsDesc": "Locate edge cases and fix errors",
  "welcome.refactor": "Refactor",
  "welcome.refactorDesc": "Improve readability and structure",
  "welcome.title": "OpenCode Assistant",
  "welcome.unitTests": "Unit Tests",
  "welcome.unitTestsDesc": "Generate comprehensive test suites",
  "cfg.tab.general": "General",
  "cfg.tab.opencode": "opencode.json",
  "cfg.tab.omo": "omo.jsonc",
  "cfg.scope.global": "Global",
  "cfg.scope.project": "Project",
  "cfg.file.path": "File",
  "cfg.file.missing": "This file does not exist yet.",
  "cfg.file.create": "Create file",
  "cfg.file.parseError": "This file has a JSON parse error and is shown read-only. Fix the syntax to edit it here.",
  "cfg.file.readOnly": "Read-only",
  "cfg.file.saved": "Saved",
  "cfg.file.conflict": "The file changed on disk after it was loaded. Reload to discard your edits, or force-save to overwrite.",
  "cfg.action.reload": "Reload",
  "cfg.action.force": "Force save",
  "cfg.notice.deprecated": "Deprecated keys detected: {keys}. They are displayed read-only and are never modified or created by this editor.",
  "cfg.notice.unknown": "Unknown keys present: {keys}. They are preserved untouched when saving.",
  "cfg.notice.legacy": "A legacy oh-my-openagent config was found at {path}. It is shown for reference only and is never written.",
  "cfg.notice.profiles": "The profiles section is managed by oh-my-opencode itself and is read-only here.",
  "cfg.notice.sharedBase": "Keys above live outside the [opencode] block and form the shared base: project files override global files, and the [opencode] block below overrides this base.",
  "cfg.notice.noWorkspace": "No workspace folder is open, so the project-level configuration is unavailable.",
  "cfg.advanced.title": "Advanced",
  "cfg.records.add": "Add entry",
  "cfg.records.remove": "Remove",
  "cfg.kv.add": "Add entry",
  "cfg.kv.key": "Key",
  "cfg.kv.value": "Value",
  "cfg.list.add": "Add item",
  "cfg.masked.set": "Set value",
  "cfg.masked.clear": "Clear",
  "cfg.masked.isSet": "Set",
  "cfg.preview.title": "JSON preview",
  "cfg.sec.oc.general": "General",
  "cfg.sec.oc.plugins": "Plugins",
  "cfg.sec.oc.permission": "Permissions",
  "cfg.sec.oc.agents": "Agents",
  "cfg.sec.oc.mcp": "MCP servers",
  "cfg.sec.oc.providers": "Providers",
  "cfg.sec.oc.runtime": "Runtime",
  "cfg.sec.oc.server": "Server",
  "cfg.sec.oc.commands": "Commands",
  "cfg.sec.oc.formatter": "Formatters",
  "cfg.sec.oc.lsp": "LSP servers",
  "cfg.sec.oc.watcher": "File watcher",
  "cfg.sec.oc.tools": "Tools",
  "cfg.sec.oc.compaction": "Compaction",
  "cfg.sec.oc.attachment": "Attachments",
  "cfg.sec.oc.experimental": "Experimental",
  "cfg.sec.oc.enterprise": "Enterprise",
  "cfg.sec.oc.skills": "Skills",
  "cfg.sec.oc.references": "References",
  "cfg.sec.oc.schema": "Schema & metadata",
  "cfg.sec.omo.agents": "Agents",
  "cfg.sec.omo.categories": "Categories",
  "cfg.sec.omo.disabled": "Disabled items",
  "cfg.sec.omo.backgroundTask": "Background tasks",
  "cfg.sec.omo.sisyphus": "Sisyphus",
  "cfg.sec.omo.memory": "Memory",
  "cfg.sec.omo.runtimeFallback": "Runtime fallback",
  "cfg.sec.omo.modelCapabilities": "Model capabilities",
  "cfg.sec.omo.tmux": "tmux",
  "cfg.sec.omo.gitMaster": "Git master",
  "cfg.sec.omo.browserAutomation": "Browser automation",
  "cfg.sec.omo.codegraph": "Codegraph",
  "cfg.sec.omo.claudeCode": "Claude Code",
  "cfg.sec.omo.integrations": "Integrations",
  "cfg.sec.omo.experimental": "Experimental",
  "cfg.sec.omo.other": "Other advanced",
  "cfg.sec.omo.shared": "Shared base",
  "cfg.f.action": "Action",
  "cfg.f.agent": "Agent",
  "cfg.f.agentDefinitions": "Agent definitions",
  "cfg.f.agentOrder": "Agent order",
  "cfg.f.agentPaneMinWidth": "Agent pane minimum width",
  "cfg.f.agents": "Agents",
  "cfg.f.aggressive": "Aggressive",
  "cfg.f.aggressiveTruncation": "Aggressive truncation",
  "cfg.f.allowedCommands": "Allowed commands",
  "cfg.f.allowedSubagents": "Allowed subagents",
  "cfg.f.allowedTools": "Allowed tools",
  "cfg.f.allowNonGptModel": "Allow non-GPT models",
  "cfg.f.anthropicProvider": "Anthropic provider",
  "cfg.f.api": "API",
  "cfg.f.apiKey": "API key",
  "cfg.f.argumentHint": "Argument hint",
  "cfg.f.attachment": "Attachments",
  "cfg.f.authorizedDiscordUserIds": "Authorized Discord user IDs",
  "cfg.f.auto": "Automatic",
  "cfg.f.autoCommit": "Auto-commit",
  "cfg.f.autoInit": "Auto-initialize",
  "cfg.f.autoProvision": "Auto-provision",
  "cfg.f.autoRefreshOnStart": "Auto-refresh on start",
  "cfg.f.autoResize": "Auto-resize",
  "cfg.f.autoSelectMax": "Auto-select maximum",
  "cfg.f.autoSelectMaxChars": "Auto-select max characters",
  "cfg.f.autoshare": "Auto-share",
  "cfg.f.autoStart": "Auto-start",
  "cfg.f.autoUpdate": "Auto-update",
  "cfg.f.autoupdate": "Auto-update",
  "cfg.f.babysitting": "Babysitting",
  "cfg.f.backendType": "Backend type",
  "cfg.f.background": "Run in background",
  "cfg.f.backgroundTask": "Background tasks",
  "cfg.f.baseDir": "Base directory",
  "cfg.f.baseURL": "Base URL",
  "cfg.f.bash": "Bash",
  "cfg.f.batchMaxBytes": "Batch max bytes",
  "cfg.f.batchMaxLines": "Batch max lines",
  "cfg.f.batchTool": "Batch tool",
  "cfg.f.blacklist": "Blacklist",
  "cfg.f.branch": "Branch",
  "cfg.f.browserAutomationEngine": "Browser automation engine",
  "cfg.f.budgetTokens": "Thinking budget (tokens)",
  "cfg.f.cacheRead": "Cache read",
  "cfg.f.cacheWrite": "Cache write",
  "cfg.f.callbackPort": "OAuth callback port",
  "cfg.f.categories": "Categories",
  "cfg.f.category": "Category",
  "cfg.f.chunkTimeout": "Chunk timeout (ms)",
  "cfg.f.circuitBreaker": "Circuit breaker",
  "cfg.f.claudeCode": "Claude Code",
  "cfg.f.claudeCodeCompat": "Claude Code compatibility",
  "cfg.f.clientId": "OAuth client ID",
  "cfg.f.clientSecret": "OAuth client secret",
  "cfg.f.codegraph": "Codegraph",
  "cfg.f.color": "Color",
  "cfg.f.command": "Command",
  "cfg.f.commands": "Commands",
  "cfg.f.commentChecker": "Comment checker",
  "cfg.f.commitFooter": "Commit footer",
  "cfg.f.compaction": "Compaction",
  "cfg.f.compatibility": "Compatibility",
  "cfg.f.compileWarnTokens": "Compile warn tokens",
  "cfg.f.consecutiveThreshold": "Consecutive threshold",
  "cfg.f.context": "Context (tokens)",
  "cfg.f.contextOver200k": "Context over 200K",
  "cfg.f.continueLoopOnDeny": "Continue loop on deny",
  "cfg.f.cooldownSeconds": "Cooldown (seconds)",
  "cfg.f.cors": "CORS origins",
  "cfg.f.cost": "Cost",
  "cfg.f.createdAt": "Created at",
  "cfg.f.customPrompt": "Custom prompt",
  "cfg.f.cwd": "Working directory",
  "cfg.f.daemon": "Daemon",
  "cfg.f.dag": "DAG limits",
  "cfg.f.debounceSettles": "Debounce settle time (ms)",
  "cfg.f.deduplication": "Deduplication",
  "cfg.f.defaultAgent": "Default agent",
  "cfg.f.defaultBuilderEnabled": "Default builder enabled",
  "cfg.f.defaultConcurrency": "Default concurrency",
  "cfg.f.defaultExecutionMode": "Default execution mode",
  "cfg.f.defaultMaxIterations": "Default max iterations",
  "cfg.f.defaultMode": "Default mode",
  "cfg.f.defaultMs": "Default wait (ms)",
  "cfg.f.defaultRunAgent": "Default run agent",
  "cfg.f.description": "Description",
  "cfg.f.disable": "Disable",
  "cfg.f.disabled": "Disabled",
  "cfg.f.disabledAgents": "Disabled agents",
  "cfg.f.disabledCommands": "Disabled commands",
  "cfg.f.disabledHooks": "Disabled hooks",
  "cfg.f.disabledKeywords": "Disabled keywords",
  "cfg.f.disabledMcps": "Disabled MCPs",
  "cfg.f.disabledProviders": "Disabled providers",
  "cfg.f.disabledSkills": "Disabled skills",
  "cfg.f.disabledTools": "Disabled tools",
  "cfg.f.disableLiveParentWakeRouting": "Disable live parent wake routing",
  "cfg.f.disableOmoEnv": "Disable OMO environment",
  "cfg.f.disablePasteSummary": "Disable paste summary",
  "cfg.f.disallowedTools": "Disallowed tools",
  "cfg.f.discordBotToken": "Discord bot token",
  "cfg.f.discordChannelId": "Discord channel ID",
  "cfg.f.discordMention": "Discord mention",
  "cfg.f.displayName": "Display name",
  "cfg.f.doomLoop": "Doom loop",
  "cfg.f.dream": "Dream",
  "cfg.f.dynamicContextPruning": "Dynamic context pruning",
  "cfg.f.edit": "Edit",
  "cfg.f.editNotice": "Edit notice",
  "cfg.f.effect": "Effect",
  "cfg.f.enable": "Enable",
  "cfg.f.enabled": "Enabled",
  "cfg.f.enabledExpansions": "Enabled expansions",
  "cfg.f.enabledProviders": "Enabled providers",
  "cfg.f.enterprise": "Enterprise",
  "cfg.f.enterpriseUrl": "Enterprise URL",
  "cfg.f.env": "Environment variables",
  "cfg.f.environment": "Environment variables",
  "cfg.f.everyUserTurns": "Every N user turns",
  "cfg.f.excludedRoots": "Excluded roots",
  "cfg.f.executionMode": "Execution mode",
  "cfg.f.experimental": "Experimental",
  "cfg.f.extensions": "File extensions",
  "cfg.f.externalDirectory": "External directories",
  "cfg.f.facts": "Facts",
  "cfg.f.fallbackModels": "Fallback models",
  "cfg.f.family": "Family",
  "cfg.f.field": "Field",
  "cfg.f.forceEnable": "Force-enable",
  "cfg.f.formatter": "Formatter",
  "cfg.f.from": "From",
  "cfg.f.gateway": "Gateway",
  "cfg.f.gateways": "Gateways",
  "cfg.f.gitEnvPrefix": "Git env prefix",
  "cfg.f.gitMaster": "Git master",
  "cfg.f.glob": "Glob",
  "cfg.f.goal": "Goal",
  "cfg.f.grep": "Grep",
  "cfg.f.hashlineEdit": "Hashline edit",
  "cfg.f.headers": "Headers",
  "cfg.f.headerTimeout": "Header timeout (ms)",
  "cfg.f.heartbeatMs": "Heartbeat (ms)",
  "cfg.f.hidden": "Hidden",
  "cfg.f.historyDefaultLimit": "History default limit",
  "cfg.f.historyMaxLimit": "History max limit",
  "cfg.f.hooks": "Hooks",
  "cfg.f.hostname": "Hostname",
  "cfg.f.i18n": "Localization (i18n)",
  "cfg.f.id": "ID",
  "cfg.f.idleMinutes": "Idle time (minutes)",
  "cfg.f.ignore": "Ignore patterns",
  "cfg.f.image": "Image",
  "cfg.f.includeCoAuthoredBy": "Include Co-authored-by",
  "cfg.f.includePrefix": "Include prefix",
  "cfg.f.initialization": "Initialization options",
  "cfg.f.input": "Input",
  "cfg.f.installDir": "Install directory",
  "cfg.f.instruction": "Instruction",
  "cfg.f.instructions": "Instruction files",
  "cfg.f.interleaved": "Interleaved",
  "cfg.f.isActive": "Active",
  "cfg.f.isolation": "Isolation",
  "cfg.f.isUnstableAgent": "Unstable agent",
  "cfg.f.keywordDetector": "Keyword detector",
  "cfg.f.kind": "Kind",
  "cfg.f.layout": "Layout",
  "cfg.f.leadAgentId": "Lead agent ID",
  "cfg.f.legacyMigrations": "Legacy migrations",
  "cfg.f.license": "License",
  "cfg.f.limit": "Limit",
  "cfg.f.lineMaxBytes": "Line max bytes",
  "cfg.f.list": "List",
  "cfg.f.liveModeEnabled": "Live mode",
  "cfg.f.locale": "Locale",
  "cfg.f.logLevel": "Log level",
  "cfg.f.lsp": "LSP",
  "cfg.f.mailboxPollIntervalMs": "Mailbox poll interval (ms)",
  "cfg.f.mainPaneMinWidth": "Main pane minimum width",
  "cfg.f.mainPaneSize": "Main pane size",
  "cfg.f.maxBase64Bytes": "Max base64 bytes",
  "cfg.f.maxBytes": "Max bytes",
  "cfg.f.maxDepth": "Max depth",
  "cfg.f.maxEntries": "Max entries",
  "cfg.f.maxEntryChars": "Max entry characters",
  "cfg.f.maxFallbackAttempts": "Max fallback attempts",
  "cfg.f.maxHeight": "Max height",
  "cfg.f.maxLines": "Max lines",
  "cfg.f.maxMembers": "Max members",
  "cfg.f.maxMemberTurns": "Max turns per member",
  "cfg.f.maxMessageLength": "Max message length",
  "cfg.f.maxMessagesPerRun": "Max messages per run",
  "cfg.f.maxMonitorsPerSession": "Max monitors per session",
  "cfg.f.maxMs": "Max wait (ms)",
  "cfg.f.maxNodesPerRun": "Max nodes per run",
  "cfg.f.maxParallelMembers": "Max parallel members",
  "cfg.f.maxPromptBytes": "Max prompt bytes",
  "cfg.f.maxPromptTokens": "Max prompt tokens",
  "cfg.f.maxRunsPerSession": "Max runs per session",
  "cfg.f.maxRuntimeMs": "Max runtime (ms)",
  "cfg.f.maxSteps": "Max steps",
  "cfg.f.maxTokens": "Max tokens",
  "cfg.f.maxToolCalls": "Max tool calls",
  "cfg.f.maxTools": "Max tools",
  "cfg.f.maxTurns": "Max turns",
  "cfg.f.maxWallClockMinutes": "Max total duration (minutes)",
  "cfg.f.maxWidth": "Max width",
  "cfg.f.mcp": "MCP",
  "cfg.f.mcpEnvAllowlist": "MCP env allowlist",
  "cfg.f.mcpTimeout": "MCP timeout (ms)",
  "cfg.f.mdns": "mDNS discovery",
  "cfg.f.mdnsDomain": "mDNS domain",
  "cfg.f.members": "Members",
  "cfg.f.memory": "Memory",
  "cfg.f.merge": "Merge",
  "cfg.f.messagePayloadMaxBytes": "Message payload max bytes",
  "cfg.f.messageStalenessTimeoutMs": "Message staleness timeout (ms)",
  "cfg.f.metadata": "Metadata",
  "cfg.f.method": "Method",
  "cfg.f.migrations": "Migrations",
  "cfg.f.minHoursBetween": "Minimum hours between",
  "cfg.f.minMs": "Min wait (ms)",
  "cfg.f.modalities": "Modalities",
  "cfg.f.mode": "Mode",
  "cfg.f.model": "Model",
  "cfg.f.modelCapabilities": "Model capabilities",
  "cfg.f.modelConcurrency": "Per-model concurrency",
  "cfg.f.modelFallback": "Model fallback",
  "cfg.f.modelFallbackTitle": "Model fallback title",
  "cfg.f.models": "Models",
  "cfg.f.monitor": "Monitor",
  "cfg.f.name": "Name",
  "cfg.f.newTaskSystemEnabled": "New task system",
  "cfg.f.notification": "Notification",
  "cfg.f.notifyOnFallback": "Notify on fallback",
  "cfg.f.npm": "npm package",
  "cfg.f.nudge": "Nudge",
  "cfg.f.oauth": "OAuth",
  "cfg.f.onCompaction": "On compaction",
  "cfg.f.openclaw": "OpenClaw",
  "cfg.f.openTelemetry": "OpenTelemetry",
  "cfg.f.options": "Options",
  "cfg.f.output": "Output",
  "cfg.f.path": "Path",
  "cfg.f.paths": "Paths",
  "cfg.f.pattern": "Pattern",
  "cfg.f.patternMaxLength": "Max pattern length",
  "cfg.f.people": "People",
  "cfg.f.permission": "Permission",
  "cfg.f.permissionDefault": "Default action",
  "cfg.f.plannerEnabled": "Planner enabled",
  "cfg.f.playwrightMcpArgs": "Playwright MCP arguments",
  "cfg.f.plugin": "Plugins",
  "cfg.f.pluginLoadTimeoutMs": "Plugin load timeout (ms)",
  "cfg.f.plugins": "Plugins",
  "cfg.f.pluginsOverride": "Plugins override",
  "cfg.f.policies": "Policies",
  "cfg.f.pollIntervalMs": "Poll interval (ms)",
  "cfg.f.port": "Port",
  "cfg.f.preemptiveCompaction": "Preemptive compaction",
  "cfg.f.preserveRecentTokens": "Preserve recent tokens",
  "cfg.f.primaryTools": "Primary-agent-only tools",
  "cfg.f.profiles": "Profiles",
  "cfg.f.prompt": "Prompt",
  "cfg.f.promptAppend": "Prompt append",
  "cfg.f.protectedTools": "Protected tools",
  "cfg.f.provider": "Provider",
  "cfg.f.providerConcurrency": "Per-provider concurrency",
  "cfg.f.providerOptions": "Provider options",
  "cfg.f.prune": "Prune old tool outputs",
  "cfg.f.purgeErrors": "Purge errors",
  "cfg.f.question": "Question",
  "cfg.f.ralphLoop": "Ralph loop",
  "cfg.f.rateLimitPerMinute": "Rate limit per minute",
  "cfg.f.read": "Read",
  "cfg.f.reasoning": "Reasoning",
  "cfg.f.reasoningEffort": "Reasoning effort",
  "cfg.f.reattachOnReconcile": "Reattach on reconcile",
  "cfg.f.recipientUnreadMaxBytes": "Recipient unread max bytes",
  "cfg.f.recursive": "Recursive",
  "cfg.f.redirectUri": "OAuth redirect URI",
  "cfg.f.reference": "Reference",
  "cfg.f.references": "References",
  "cfg.f.reflection": "Reflection",
  "cfg.f.refreshTimeoutMs": "Refresh timeout (ms)",
  "cfg.f.releaseDate": "Release date",
  "cfg.f.remote": "Remote",
  "cfg.f.replacePlan": "Replace plan",
  "cfg.f.replyListener": "Reply listener",
  "cfg.f.repository": "Repository",
  "cfg.f.reserved": "Reserved tokens",
  "cfg.f.residencyMaxChildren": "Resident max children",
  "cfg.f.resource": "Resource",
  "cfg.f.restorePrimaryAfterCooldown": "Restore primary after cooldown",
  "cfg.f.resumeChildren": "Resume children",
  "cfg.f.retentionDays": "Retention (days)",
  "cfg.f.retryOnErrors": "Retry on errors",
  "cfg.f.ringMaxLines": "Ring buffer max lines",
  "cfg.f.runtimeFallback": "Runtime fallback",
  "cfg.f.safeHookCreation": "Safe hook creation",
  "cfg.f.sandbox": "Sandbox",
  "cfg.f.schema": "JSON schema",
  "cfg.f.scope": "Scope",
  "cfg.f.search": "Search",
  "cfg.f.server": "Server",
  "cfg.f.sessionGoneTimeoutMs": "Session-gone timeout (ms)",
  "cfg.f.sessionPermission": "Session permission",
  "cfg.f.sessionStartCooldownMs": "Session start cooldown (ms)",
  "cfg.f.setCacheKey": "Set cache key",
  "cfg.f.share": "Sharing",
  "cfg.f.shell": "Shell",
  "cfg.f.shutdownLaunch": "Shutdown launch",
  "cfg.f.sidebar": "Sidebar",
  "cfg.f.sisyphus": "Sisyphus",
  "cfg.f.sisyphusAgent": "Sisyphus agent",
  "cfg.f.skill": "Skill",
  "cfg.f.skills": "Skills",
  "cfg.f.smallModel": "Small model",
  "cfg.f.snapshot": "Snapshot",
  "cfg.f.soul": "Soul",
  "cfg.f.sourceUrl": "Source URL",
  "cfg.f.sources": "Sources",
  "cfg.f.staleTimeoutMs": "Stale timeout (ms)",
  "cfg.f.startWork": "Start work",
  "cfg.f.stateDir": "State directory",
  "cfg.f.status": "Status",
  "cfg.f.stepCount": "Step count",
  "cfg.f.steps": "Steps",
  "cfg.f.storagePath": "Storage path",
  "cfg.f.strategies": "Strategies",
  "cfg.f.subagentDepth": "Subagent depth",
  "cfg.f.subagentType": "Subagent type",
  "cfg.f.subscriberRing": "Subscriber ring size",
  "cfg.f.subscriptions": "Subscriptions",
  "cfg.f.subtask": "Subtask",
  "cfg.f.supersedeWrites": "Supersede writes",
  "cfg.f.sync": "Sync",
  "cfg.f.syncPollTimeoutMs": "Sync poll timeout (ms)",
  "cfg.f.tailTurns": "Tail turns kept verbatim",
  "cfg.f.task": "Task",
  "cfg.f.taskCleanupDelayMs": "Task cleanup delay (ms)",
  "cfg.f.taskListId": "Task list ID",
  "cfg.f.tasks": "Tasks",
  "cfg.f.taskSystem": "Task system",
  "cfg.f.taskTtlMs": "Task TTL (ms)",
  "cfg.f.tdd": "TDD",
  "cfg.f.team": "Team",
  "cfg.f.teamAllowedPaths": "Team allowed paths",
  "cfg.f.teamMode": "Team mode",
  "cfg.f.telegramBotToken": "Telegram bot token",
  "cfg.f.telegramChatId": "Telegram chat ID",
  "cfg.f.telemetry": "Telemetry",
  "cfg.f.temperature": "Temperature",
  "cfg.f.template": "Template",
  "cfg.f.textVerbosity": "Text verbosity",
  "cfg.f.thinking": "Thinking",
  "cfg.f.timeout": "Timeout (ms)",
  "cfg.f.timeoutMinutes": "Timeout (minutes)",
  "cfg.f.timeoutMs": "Timeout (ms)",
  "cfg.f.timeoutSeconds": "Timeout (seconds)",
  "cfg.f.tmux": "tmux",
  "cfg.f.tmuxVisualization": "tmux visualization",
  "cfg.f.todowrite": "TodoWrite",
  "cfg.f.toolCall": "Tool call",
  "cfg.f.toolExposure": "Tool exposure",
  "cfg.f.toolOutput": "Tool output",
  "cfg.f.tools": "Tools",
  "cfg.f.topP": "Top-p",
  "cfg.f.trigger": "Trigger",
  "cfg.f.truncateAllToolOutputs": "Truncate all tool outputs",
  "cfg.f.ttlMs": "TTL (ms)",
  "cfg.f.tui": "TUI",
  "cfg.f.turnProtection": "Turn protection",
  "cfg.f.turns": "Turns",
  "cfg.f.type": "Type",
  "cfg.f.ultrawork": "Ultrawork",
  "cfg.f.unavailableCategories": "Unavailable categories warning",
  "cfg.f.url": "URL",
  "cfg.f.urls": "URLs",
  "cfg.f.username": "Username",
  "cfg.f.variant": "Variant",
  "cfg.f.variants": "Variants",
  "cfg.f.version": "Version",
  "cfg.f.wait": "Wait",
  "cfg.f.warnings": "Warnings",
  "cfg.f.warnUnavailable": "Warn when unavailable",
  "cfg.f.watchDebounceMs": "Watch debounce (ms)",
  "cfg.f.watcher": "Watcher",
  "cfg.f.webfetch": "WebFetch",
  "cfg.f.websearch": "WebSearch",
  "cfg.f.whitelist": "Whitelist",
  "cfg.f.worktreePath": "Worktree path",
  "cfg.f.writeNotice": "Write notice",
};

/**
 * Traditional Chinese (zh-TW) table. Tone follows VS Code's own zh-tw
 * localization conventions (工作階段, 傳送, 權限, 模型, 設定, 偵錯).
 */
export const zhTW: Record<StringId, string> = {
  "app.loading": "載入中…",
  "app.name": "OpenCode Panel",
  "commands.empty": "沒有符合的指令",
  "commands.title": "指令",
  "composer.abort": "停止產生",
  "composer.draftRestored": "已還原未送出的草稿",
  "composer.autoMode.off": "OFF",
  "composer.autoMode.on": "ON",
  "composer.autoMode.title": "自動執行模式 (Auto Mode)",
  "composer.cancel": "取消",
  "composer.effort.none": "此模型無可用的思考強度設定",
  "composer.effort.title": "思考強度 (Effort)",
  "composer.variant.fast": "Fast (關閉思考)",
  "composer.variant.high": "High (深度思考)",
  "composer.variant.low": "Low (快速思考)",
  "composer.variant.max": "Max (極致推理)",
  "composer.variant.medium": "Medium (標準推理)",
  "composer.variant.off": "Off (關閉思考)",
  "composer.variant.on": "On (啟用思考)",
  "composer.variant.thinking": "Thinking (啟用思考)",
  "composer.optionsMenu": "設定與功能選單",
  "composer.openSettings": "開啟設定頁面...",
  "composer.placeholder": "向 opencode 提問...",
  "composer.queued": "排隊等待中：{text}",
  "composer.send": "傳送",
  "common.cancel": "取消",
  "common.close": "關閉",
  "common.confirm": "確認",
  "capability.hidden": "連線的伺服器不支援此功能",
  "chat.usage": "工作階段 Token 用量",
  "chat.usage.input": "輸入",
  "chat.usage.output": "輸出",
  "chat.usage.reasoning": "推理",
  "dock.diffs.empty": "此工作階段尚無檔案變更",
  "dock.diffs.fileLink": "檔案 ↗",
  "dock.diffs.openDiff": "開啟差異比對",
  "dock.diffs.openFile": "開啟檔案",
  "dock.diffs.openUnavailable": "無法開啟差異比對：找不到此工作階段",
  "dock.diffs.title": "檔案變更",
  "dock.todos.empty": "尚無待辦事項",
  "dock.todos.title": "待辦事項",
  "error.boundary.title": "發生錯誤",
  "menu.more": "更多動作",
  "menu.openTui": "開啟 TUI",
  "mention.count": "共 {count} 項",
  "mention.paletteHint": "提及檔案或符號",
  "mcp.nativeOnly": "僅列出原生設定的 MCP 伺服器",
  "mcp.omoNote": "已偵測到 oh-my-opencode：外掛程式可能注入未列於此處的其他 MCP。",
  "mcp.title": "MCP 伺服器",
  "chat.jumpBack": "回到此處 (Jump to prompt)",
  "chat.scrollBottom": "捲動至最新訊息",
  "chat.systemReminder.label": "系統提醒 · 背景任務通知",
  "messages.collapseTool": "摺疊工具呼叫詳細資訊",
  "messages.empty": "尚無訊息，傳送提示以開始對話。",
  "messages.expandTool": "展開工具呼叫詳細資訊",
  "messages.export": "匯出對話紀錄",
  "messages.regenerate": "重新產生",
  "messages.revert": "還原至此處",
  "messages.revertConfirm": "確定要將工作階段還原到此訊息嗎？此處之後的檔案變更將被復原。",
  "messages.shell": "執行 Shell 指令",
  "messages.shellPlaceholder": "例如：git status",
  "messages.summarize": "摘要並壓縮工作階段",
  "messages.thinking": "思考中",
  "messages.unrevert": "復原已還原的訊息",
  "permission.allowAlways": "一律允許",
  "permission.allowOnce": "允許一次",
  "permission.approvedState": "已核准",
  "permission.expired": "此權限要求已過期",
  "permission.reject": "拒絕",
  "permission.title": "需要權限",
  "picker.agent.customBadge": "自訂",
  "picker.agent.customPickedToast": "已選擇自訂智慧體「{name}」。",
  "picker.agent.lockedToast": "智慧體「{name}」已鎖定專屬模型「{model}」。",
  "picker.agent.title": "選擇代理",
  "picker.model.lockedReason": "🔒 智慧體「{name}」已鎖定使用專屬模型「{model}」，無法手動切換。",
  "picker.model.lockedToast": "智慧體「{name}」已綁定專屬模型「{model}」。若要自由切換模型，請切換至通用智慧體 (build / general)。",
  "picker.model.pickedWarningToast": "已設定模型為「{model}」。目前使用中的自訂智慧體「{name}」若設定了專屬模型，後端將優先以智慧體模型為主。若要完全自由指定模型，請切換至 build / general 通用智慧體。",
  "picker.model.title": "選擇模型",
  "question.answerPlaceholder": "請在此輸入回答...",
  "question.completed": "已完成",
  "question.customPlaceholder": "其他補充回答 (選填)...",
  "question.selectedPrefix": "已選擇：",
  "question.submit": "送出回答",
  "question.title": "opencode 正在詢問問題",
  "question.unavailable": "連線的伺服器不支援從面板回答問題。",
  "server.oldVersion": "連線的伺服器版本低於建議版本，部分功能已隱藏。",
  "server.status.attached": "伺服器執行中（已附加）",
  "server.status.connected": "伺服器已連線",
  "server.status.lost": "與 opencode 伺服器的連線已中斷",
  "server.status.managed": "伺服器執行中（由此擴充功能管理）",
  "server.status.probing": "正在連線到伺服器…",
  "server.status.retry": "重試",
  "server.status.stopped": "伺服器已停止",
  "sessions.closeHistory": "關閉工作階段歷程",
  "sessions.compress": "壓縮",
  "sessions.delete": "刪除",
  "sessions.deleteConfirm": "確定要刪除此工作階段嗎？此操作無法復原。",
  "sessions.empty": "尚無工作階段，請建立一個新的工作階段開始對話。",
  "sessions.fork": "建立分支",
  "sessions.history": "歷程",
  "sessions.historyTitle": "工作階段歷程",
  "sessions.new": "新增工作階段",
  "sessions.rename": "重新命名",
  "sessions.renamePrompt": "輸入新的工作階段標題",
  "sessions.searchPlaceholder": "搜尋工作階段…",
  "sessions.share": "分享",
  "sessions.shareCopied": "已複製分享連結到剪貼簿",
  "sessions.title": "工作階段",
  "sessions.unshare": "停止分享",
  "sessions.viewAll": "檢視全部 ({count})",
  "settings.apply": "套用",
  "settings.compress": "壓縮",
  "settings.connectionFailed": "連線失敗",
  "settings.connectionOk": "連線成功",
  "settings.enumOption.auto": "自動（跟隨 VS Code）",
  "settings.enumOption.en": "English",
  "settings.enumOption.zhTW": "繁體中文",
  "settings.field.autoStartServer": "自動啟動伺服器",
  "settings.field.binaryPath": "opencode 執行檔路徑",
  "settings.field.chatFontFamily": "聊天字型",
  "settings.field.chatFontSize": "聊天字型大小",
  "settings.field.debugLogs": "偵錯記錄",
  "settings.field.hostname": "主機名稱",
  "settings.field.language": "介面語言",
  "settings.field.minimumServerVersion": "最低伺服器版本",
  "settings.field.port": "連接埠",
  "settings.field.serverArgs": "伺服器啟動引數",
  "settings.field.serverPassword": "伺服器密碼",
  "settings.field.serverUrl": "伺服器 URL",
  "settings.field.serverUsername": "伺服器使用者名稱（選用）",
  "settings.placeholder": "這裡暫時沒有可設定的項目。",
  "settings.revert": "還原",
  "settings.saveFailed": "設定儲存失敗",
  "settings.saved": "設定已儲存",
  "settings.section.appearance": "外觀",
  "settings.section.capabilities": "功能偵測",
  "settings.section.diagnostics": "診斷",
  "settings.section.server": "伺服器",
  "settings.scope.user": "使用者",
  "settings.scope.workspace": "工作區",
  "settings.secret.clear": "清除",
  "settings.secret.isSet": "已儲存",
  "settings.secret.notSet": "未設定",
  "settings.serverActionsHint": "使用命令面板啟動、停止或重新啟動伺服器。",
  "settings.testConnection": "測試連線",
  "settings.title": "設定",
  "settings.validationFailed": "值無效",
  "tool.copiedState": "已複製 ✓",
  "tool.copyLabel": "複製",
  "tool.searchPrefix": "搜尋詞：",
  "tool.searchQuery": "搜尋: {query}",
  "tool.backgroundTask": "背景任務 ({taskId})",
  "tool.omittedLinesSuffix": "... (+{count} 行省略）",
  "subagent.completedNote": "✓ 子智慧體已完成任務。",
  "subagent.fallbackTaskLabel": "任務： {title}",
  "subagent.liveIndicator": "即時執行中",
  "subagent.logStepsLabel": "執行步驟 (Subagent Logs)",
  "subagent.runningInBackground": "子智慧體背景運算中，正在執行任務...",
  "subagent.statusFinished": "調用完成",
  "subagent.statusRunning": "執行中...",
  "subagent.taskDescriptionLabel": "任務說明",
  "tool.status.completed": "已完成",
  "tool.status.failed": "失敗",
  "tool.output.collapse": "收起日誌",
  "tool.output.expand": "展開更多日誌 (+{count} 行)",
  "tool.status.pending": "等待中",
  "tool.status.running": "執行中",
  "welcome.explain": "解釋程式碼",
  "welcome.explainDesc": "分析選取的邏輯或當前檔案",
  "welcome.findBugs": "找出錯誤",
  "welcome.findBugsDesc": "定位邊界情況並修復問題",
  "welcome.refactor": "重構",
  "welcome.refactorDesc": "改善可讀性與結構",
  "welcome.title": "OpenCode 助理",
  "welcome.unitTests": "單元測試",
  "welcome.unitTestsDesc": "產生完整的測試套組",
  "cfg.tab.general": "一般",
  "cfg.tab.opencode": "opencode.json",
  "cfg.tab.omo": "omo.jsonc",
  "cfg.scope.global": "全域",
  "cfg.scope.project": "專案",
  "cfg.file.path": "檔案",
  "cfg.file.missing": "此檔案尚不存在。",
  "cfg.file.create": "建立檔案",
  "cfg.file.parseError": "此檔案的 JSON 剖析失敗，目前以唯讀顯示。請修正語法後再行編輯。",
  "cfg.file.readOnly": "唯讀",
  "cfg.file.saved": "已儲存",
  "cfg.file.conflict": "載入後此檔案已在磁碟上被修改。重新載入將捨棄您的編輯，或以強制儲存覆寫。",
  "cfg.action.reload": "重新載入",
  "cfg.action.force": "強制儲存",
  "cfg.notice.deprecated": "偵測到已棄用的鍵：{keys}。它們僅以唯讀顯示，此編輯器不會修改或建立這些鍵。",
  "cfg.notice.unknown": "存在未知的鍵：{keys}。儲存時將原樣保留。",
  "cfg.notice.legacy": "在 {path} 發現舊版 oh-my-openagent 設定，僅供參考顯示，絕不寫入。",
  "cfg.notice.profiles": "profiles 區段由 oh-my-opencode 自行管理，在此僅供唯讀檢視。",
  "cfg.notice.sharedBase": "以上鍵位於 [opencode] 區塊之外，屬於共用基底；專案檔覆寫全域檔，而下方 [opencode] 區塊會覆寫此基底。",
  "cfg.notice.noWorkspace": "未開啟工作區資料夾，因此無法使用專案層級設定。",
  "cfg.advanced.title": "進階",
  "cfg.records.add": "新增項目",
  "cfg.records.remove": "移除",
  "cfg.kv.add": "新增項目",
  "cfg.kv.key": "鍵",
  "cfg.kv.value": "值",
  "cfg.list.add": "新增一項",
  "cfg.masked.set": "設定值",
  "cfg.masked.clear": "清除",
  "cfg.masked.isSet": "已設定",
  "cfg.preview.title": "JSON 預覽",
  "cfg.sec.oc.general": "一般",
  "cfg.sec.oc.plugins": "外掛程式",
  "cfg.sec.oc.permission": "權限",
  "cfg.sec.oc.agents": "代理",
  "cfg.sec.oc.mcp": "MCP 伺服器",
  "cfg.sec.oc.providers": "提供者",
  "cfg.sec.oc.runtime": "執行階段",
  "cfg.sec.oc.server": "伺服器",
  "cfg.sec.oc.commands": "指令",
  "cfg.sec.oc.formatter": "格式化工具",
  "cfg.sec.oc.lsp": "LSP 伺服器",
  "cfg.sec.oc.watcher": "檔案監看",
  "cfg.sec.oc.tools": "工具",
  "cfg.sec.oc.compaction": "壓縮",
  "cfg.sec.oc.attachment": "附件",
  "cfg.sec.oc.experimental": "實驗性功能",
  "cfg.sec.oc.enterprise": "企業版",
  "cfg.sec.oc.skills": "技能",
  "cfg.sec.oc.references": "參照",
  "cfg.sec.oc.schema": "結構描述與中繼資料",
  "cfg.sec.omo.agents": "代理",
  "cfg.sec.omo.categories": "類別",
  "cfg.sec.omo.disabled": "停用項目",
  "cfg.sec.omo.backgroundTask": "背景工作",
  "cfg.sec.omo.sisyphus": "Sisyphus",
  "cfg.sec.omo.memory": "記憶",
  "cfg.sec.omo.runtimeFallback": "執行階段後援",
  "cfg.sec.omo.modelCapabilities": "模型能力",
  "cfg.sec.omo.tmux": "tmux",
  "cfg.sec.omo.gitMaster": "Git master",
  "cfg.sec.omo.browserAutomation": "瀏覽器自動化",
  "cfg.sec.omo.codegraph": "Codegraph",
  "cfg.sec.omo.claudeCode": "Claude Code",
  "cfg.sec.omo.integrations": "整合",
  "cfg.sec.omo.experimental": "實驗性功能",
  "cfg.sec.omo.other": "其他進階",
  "cfg.sec.omo.shared": "共用基底",
  "cfg.f.action": "動作",
  "cfg.f.agent": "代理",
  "cfg.f.agentDefinitions": "代理定義",
  "cfg.f.agentOrder": "代理順序",
  "cfg.f.agentPaneMinWidth": "代理窗格最小寬度",
  "cfg.f.agents": "代理",
  "cfg.f.aggressive": "積極模式",
  "cfg.f.aggressiveTruncation": "積極截斷",
  "cfg.f.allowedCommands": "允許的指令",
  "cfg.f.allowedSubagents": "允許的子代理",
  "cfg.f.allowedTools": "允許的工具",
  "cfg.f.allowNonGptModel": "允許非 GPT 模型",
  "cfg.f.anthropicProvider": "Anthropic 提供者",
  "cfg.f.api": "API",
  "cfg.f.apiKey": "API 金鑰",
  "cfg.f.argumentHint": "引數提示",
  "cfg.f.attachment": "附件",
  "cfg.f.authorizedDiscordUserIds": "授權的 Discord 使用者 ID",
  "cfg.f.auto": "自動",
  "cfg.f.autoCommit": "自動提交",
  "cfg.f.autoInit": "自動初始化",
  "cfg.f.autoProvision": "自動佈建",
  "cfg.f.autoRefreshOnStart": "啟動時自動重新整理",
  "cfg.f.autoResize": "自動調整大小",
  "cfg.f.autoSelectMax": "自動選取上限",
  "cfg.f.autoSelectMaxChars": "自動選取的最大字元數",
  "cfg.f.autoshare": "自動分享",
  "cfg.f.autoStart": "自動啟動",
  "cfg.f.autoUpdate": "自動更新",
  "cfg.f.autoupdate": "自動更新",
  "cfg.f.babysitting": "照看",
  "cfg.f.backendType": "後端類型",
  "cfg.f.background": "在背景執行",
  "cfg.f.backgroundTask": "背景工作",
  "cfg.f.baseDir": "基底目錄",
  "cfg.f.baseURL": "基底 URL",
  "cfg.f.bash": "Bash",
  "cfg.f.batchMaxBytes": "批次最大位元組數",
  "cfg.f.batchMaxLines": "批次最大行數",
  "cfg.f.batchTool": "批次工具",
  "cfg.f.blacklist": "黑名單",
  "cfg.f.branch": "分支",
  "cfg.f.browserAutomationEngine": "瀏覽器自動化引擎",
  "cfg.f.budgetTokens": "思考預算（Token）",
  "cfg.f.cacheRead": "快取讀取",
  "cfg.f.cacheWrite": "快取寫入",
  "cfg.f.callbackPort": "OAuth 回呼連接埠",
  "cfg.f.categories": "類別",
  "cfg.f.category": "類別",
  "cfg.f.chunkTimeout": "串流區塊逾時（毫秒）",
  "cfg.f.circuitBreaker": "熔斷器",
  "cfg.f.claudeCode": "Claude Code",
  "cfg.f.claudeCodeCompat": "Claude Code 相容性",
  "cfg.f.clientId": "OAuth 用戶端 ID",
  "cfg.f.clientSecret": "OAuth 用戶端密鑰",
  "cfg.f.codegraph": "Codegraph",
  "cfg.f.color": "色彩",
  "cfg.f.command": "指令",
  "cfg.f.commands": "指令",
  "cfg.f.commentChecker": "註解檢查",
  "cfg.f.commitFooter": "提交頁尾",
  "cfg.f.compaction": "壓縮",
  "cfg.f.compatibility": "相容性",
  "cfg.f.compileWarnTokens": "編譯警告 Token 數",
  "cfg.f.consecutiveThreshold": "連續觸發門檻",
  "cfg.f.context": "上下文（Token）",
  "cfg.f.contextOver200k": "超過 200K 上下文",
  "cfg.f.continueLoopOnDeny": "工具被拒後繼續迴圈",
  "cfg.f.cooldownSeconds": "冷卻時間（秒）",
  "cfg.f.cors": "CORS 允許來源",
  "cfg.f.cost": "費用",
  "cfg.f.createdAt": "建立時間",
  "cfg.f.customPrompt": "自訂提示詞",
  "cfg.f.cwd": "工作目錄",
  "cfg.f.daemon": "常駐行程",
  "cfg.f.dag": "DAG 限制",
  "cfg.f.debounceSettles": "去抖動延遲（毫秒）",
  "cfg.f.deduplication": "去除重複",
  "cfg.f.defaultAgent": "預設代理",
  "cfg.f.defaultBuilderEnabled": "啟用預設建構器",
  "cfg.f.defaultConcurrency": "預設並行數",
  "cfg.f.defaultExecutionMode": "預設執行模式",
  "cfg.f.defaultMaxIterations": "預設最大迭代次數",
  "cfg.f.defaultMode": "預設模式",
  "cfg.f.defaultMs": "預設等待（毫秒）",
  "cfg.f.defaultRunAgent": "預設執行代理",
  "cfg.f.description": "描述",
  "cfg.f.disable": "停用",
  "cfg.f.disabled": "已停用",
  "cfg.f.disabledAgents": "停用的代理",
  "cfg.f.disabledCommands": "停用的指令",
  "cfg.f.disabledHooks": "停用的 Hook",
  "cfg.f.disabledKeywords": "停用的關鍵字",
  "cfg.f.disabledMcps": "停用的 MCP",
  "cfg.f.disabledProviders": "停用的提供者",
  "cfg.f.disabledSkills": "停用的技能",
  "cfg.f.disabledTools": "停用的工具",
  "cfg.f.disableLiveParentWakeRouting": "停用即時喚醒父任務路由",
  "cfg.f.disableOmoEnv": "停用 OMO 環境",
  "cfg.f.disablePasteSummary": "停用貼上摘要",
  "cfg.f.disallowedTools": "禁止的工具",
  "cfg.f.discordBotToken": "Discord 機器人權杖",
  "cfg.f.discordChannelId": "Discord 頻道 ID",
  "cfg.f.discordMention": "Discord 提及",
  "cfg.f.displayName": "顯示名稱",
  "cfg.f.doomLoop": "失控迴圈",
  "cfg.f.dream": "夢境",
  "cfg.f.dynamicContextPruning": "動態上下文修剪",
  "cfg.f.edit": "編輯",
  "cfg.f.editNotice": "編輯提示",
  "cfg.f.effect": "效力",
  "cfg.f.enable": "啟用",
  "cfg.f.enabled": "已啟用",
  "cfg.f.enabledExpansions": "啟用的擴展項",
  "cfg.f.enabledProviders": "啟用的提供者",
  "cfg.f.enterprise": "企業版",
  "cfg.f.enterpriseUrl": "企業版 URL",
  "cfg.f.env": "環境變數",
  "cfg.f.environment": "環境變數",
  "cfg.f.everyUserTurns": "每隔 N 個使用者回合",
  "cfg.f.excludedRoots": "排除的根目錄",
  "cfg.f.executionMode": "執行模式",
  "cfg.f.experimental": "實驗性",
  "cfg.f.extensions": "副檔名",
  "cfg.f.externalDirectory": "外部目錄",
  "cfg.f.facts": "事實",
  "cfg.f.fallbackModels": "後援模型",
  "cfg.f.family": "系列",
  "cfg.f.field": "欄位",
  "cfg.f.forceEnable": "強制啟用",
  "cfg.f.formatter": "格式化工具",
  "cfg.f.from": "來源",
  "cfg.f.gateway": "閘道",
  "cfg.f.gateways": "閘道",
  "cfg.f.gitEnvPrefix": "Git 環境變數前綴",
  "cfg.f.gitMaster": "Git master",
  "cfg.f.glob": "Glob",
  "cfg.f.goal": "目標",
  "cfg.f.grep": "Grep",
  "cfg.f.hashlineEdit": "Hashline 編輯",
  "cfg.f.headers": "標頭",
  "cfg.f.headerTimeout": "標頭逾時（毫秒）",
  "cfg.f.heartbeatMs": "心跳間隔（毫秒）",
  "cfg.f.hidden": "隱藏",
  "cfg.f.historyDefaultLimit": "歷程預設筆數",
  "cfg.f.historyMaxLimit": "歷程最大筆數",
  "cfg.f.hooks": "Hook",
  "cfg.f.hostname": "主機名稱",
  "cfg.f.i18n": "多國語言（i18n）",
  "cfg.f.id": "ID",
  "cfg.f.idleMinutes": "閒置時間（分鐘）",
  "cfg.f.ignore": "忽略模式",
  "cfg.f.image": "圖片",
  "cfg.f.includeCoAuthoredBy": "加入 Co-authored-by",
  "cfg.f.includePrefix": "包含前綴",
  "cfg.f.initialization": "初始化選項",
  "cfg.f.input": "輸入",
  "cfg.f.installDir": "安裝目錄",
  "cfg.f.instruction": "指示",
  "cfg.f.instructions": "指示檔",
  "cfg.f.interleaved": "交錯",
  "cfg.f.isActive": "啟用中",
  "cfg.f.isolation": "隔離",
  "cfg.f.isUnstableAgent": "不穩定代理",
  "cfg.f.keywordDetector": "關鍵字偵測",
  "cfg.f.kind": "種類",
  "cfg.f.layout": "版面配置",
  "cfg.f.leadAgentId": "主導代理 ID",
  "cfg.f.legacyMigrations": "舊版移轉",
  "cfg.f.license": "授權條款",
  "cfg.f.limit": "上限",
  "cfg.f.lineMaxBytes": "單行最大位元組數",
  "cfg.f.list": "清單",
  "cfg.f.liveModeEnabled": "即時模式",
  "cfg.f.locale": "地區語系",
  "cfg.f.logLevel": "記錄層級",
  "cfg.f.lsp": "LSP",
  "cfg.f.mailboxPollIntervalMs": "信箱輪詢間隔（毫秒）",
  "cfg.f.mainPaneMinWidth": "主窗格最小寬度",
  "cfg.f.mainPaneSize": "主窗格大小",
  "cfg.f.maxBase64Bytes": "最大 base64 位元組數",
  "cfg.f.maxBytes": "最大位元組數",
  "cfg.f.maxDepth": "最大深度",
  "cfg.f.maxEntries": "最大項目數",
  "cfg.f.maxEntryChars": "單項最大字元數",
  "cfg.f.maxFallbackAttempts": "最大後援嘗試次數",
  "cfg.f.maxHeight": "最大高度",
  "cfg.f.maxLines": "最大行數",
  "cfg.f.maxMembers": "最大成員數",
  "cfg.f.maxMemberTurns": "每成員最大回合數",
  "cfg.f.maxMessageLength": "訊息最大長度",
  "cfg.f.maxMessagesPerRun": "每次執行最大訊息數",
  "cfg.f.maxMonitorsPerSession": "每工作階段最大監視器數",
  "cfg.f.maxMs": "最大等待（毫秒）",
  "cfg.f.maxNodesPerRun": "每次執行最大節點數",
  "cfg.f.maxParallelMembers": "最大並行成員數",
  "cfg.f.maxPromptBytes": "提示詞最大位元組數",
  "cfg.f.maxPromptTokens": "提示詞最大 Token 數",
  "cfg.f.maxRunsPerSession": "每工作階段最大執行次數",
  "cfg.f.maxRuntimeMs": "最大執行時間（毫秒）",
  "cfg.f.maxSteps": "最大步驟數",
  "cfg.f.maxTokens": "最大 Token 數",
  "cfg.f.maxToolCalls": "最大工具呼叫數",
  "cfg.f.maxTools": "最大工具數",
  "cfg.f.maxTurns": "最大回合數",
  "cfg.f.maxWallClockMinutes": "最大總時長（分鐘）",
  "cfg.f.maxWidth": "最大寬度",
  "cfg.f.mcp": "MCP",
  "cfg.f.mcpEnvAllowlist": "MCP 環境變數允許清單",
  "cfg.f.mcpTimeout": "MCP 逾時（毫秒）",
  "cfg.f.mdns": "mDNS 探索",
  "cfg.f.mdnsDomain": "mDNS 網域",
  "cfg.f.members": "成員",
  "cfg.f.memory": "記憶",
  "cfg.f.merge": "合併",
  "cfg.f.messagePayloadMaxBytes": "訊息酬載最大位元組數",
  "cfg.f.messageStalenessTimeoutMs": "訊息陳舊逾時（毫秒）",
  "cfg.f.metadata": "中繼資料",
  "cfg.f.method": "方法",
  "cfg.f.migrations": "移轉",
  "cfg.f.minHoursBetween": "最小間隔（小時）",
  "cfg.f.minMs": "最小等待（毫秒）",
  "cfg.f.modalities": "模態",
  "cfg.f.mode": "模式",
  "cfg.f.model": "模型",
  "cfg.f.modelCapabilities": "模型能力",
  "cfg.f.modelConcurrency": "每模型並行數",
  "cfg.f.modelFallback": "模型後援",
  "cfg.f.modelFallbackTitle": "模型後援標題",
  "cfg.f.models": "模型",
  "cfg.f.monitor": "監視器",
  "cfg.f.name": "名稱",
  "cfg.f.newTaskSystemEnabled": "新工作系統",
  "cfg.f.notification": "通知",
  "cfg.f.notifyOnFallback": "後援時通知",
  "cfg.f.npm": "npm 套件",
  "cfg.f.nudge": "提醒推送",
  "cfg.f.oauth": "OAuth",
  "cfg.f.onCompaction": "壓縮時",
  "cfg.f.openclaw": "OpenClaw",
  "cfg.f.openTelemetry": "OpenTelemetry",
  "cfg.f.options": "選項",
  "cfg.f.output": "輸出",
  "cfg.f.path": "路徑",
  "cfg.f.paths": "路徑",
  "cfg.f.pattern": "比對模式",
  "cfg.f.patternMaxLength": "模式最大長度",
  "cfg.f.people": "人員",
  "cfg.f.permission": "權限",
  "cfg.f.permissionDefault": "預設動作",
  "cfg.f.plannerEnabled": "啟用規劃器",
  "cfg.f.playwrightMcpArgs": "Playwright MCP 引數",
  "cfg.f.plugin": "外掛程式",
  "cfg.f.pluginLoadTimeoutMs": "外掛載入逾時（毫秒）",
  "cfg.f.plugins": "外掛程式",
  "cfg.f.pluginsOverride": "外掛覆寫",
  "cfg.f.policies": "政策",
  "cfg.f.pollIntervalMs": "輪詢間隔（毫秒）",
  "cfg.f.port": "連接埠",
  "cfg.f.preemptiveCompaction": "預先壓縮",
  "cfg.f.preserveRecentTokens": "保留近期 Token 數",
  "cfg.f.primaryTools": "僅主代理工具",
  "cfg.f.profiles": "設定檔",
  "cfg.f.prompt": "提示詞",
  "cfg.f.promptAppend": "提示詞附加",
  "cfg.f.protectedTools": "受保護的工具",
  "cfg.f.provider": "提供者",
  "cfg.f.providerConcurrency": "每提供者並行數",
  "cfg.f.providerOptions": "提供者選項",
  "cfg.f.prune": "清除舊工具輸出",
  "cfg.f.purgeErrors": "清除錯誤紀錄",
  "cfg.f.question": "問題",
  "cfg.f.ralphLoop": "Ralph 迴圈",
  "cfg.f.rateLimitPerMinute": "每分鐘速率限制",
  "cfg.f.read": "讀取",
  "cfg.f.reasoning": "推理",
  "cfg.f.reasoningEffort": "推理強度",
  "cfg.f.reattachOnReconcile": "調和時重新附加",
  "cfg.f.recipientUnreadMaxBytes": "收件者未讀最大位元組數",
  "cfg.f.recursive": "遞迴",
  "cfg.f.redirectUri": "OAuth 重新導向 URI",
  "cfg.f.reference": "參照",
  "cfg.f.references": "參照",
  "cfg.f.reflection": "反思",
  "cfg.f.refreshTimeoutMs": "重新整理逾時（毫秒）",
  "cfg.f.releaseDate": "發布日期",
  "cfg.f.remote": "遠端",
  "cfg.f.replacePlan": "取代計畫",
  "cfg.f.replyListener": "回覆監聽器",
  "cfg.f.repository": "存放庫",
  "cfg.f.reserved": "保留 Token 數",
  "cfg.f.residencyMaxChildren": "常駐最大子任務數",
  "cfg.f.resource": "資源",
  "cfg.f.restorePrimaryAfterCooldown": "冷卻後還原主力代理",
  "cfg.f.resumeChildren": "恢復子任務",
  "cfg.f.retentionDays": "保留天數",
  "cfg.f.retryOnErrors": "錯誤時重試",
  "cfg.f.ringMaxLines": "環形緩衝最大行數",
  "cfg.f.runtimeFallback": "執行階段後援",
  "cfg.f.safeHookCreation": "安全建立 Hook",
  "cfg.f.sandbox": "沙箱",
  "cfg.f.schema": "JSON 結構描述",
  "cfg.f.scope": "範圍",
  "cfg.f.search": "搜尋",
  "cfg.f.server": "伺服器",
  "cfg.f.sessionGoneTimeoutMs": "工作階段消失逾時（毫秒）",
  "cfg.f.sessionPermission": "工作階段權限",
  "cfg.f.sessionStartCooldownMs": "工作階段啟動冷卻（毫秒）",
  "cfg.f.setCacheKey": "設定快取鍵",
  "cfg.f.share": "分享",
  "cfg.f.shell": "Shell",
  "cfg.f.shutdownLaunch": "關閉時啟動",
  "cfg.f.sidebar": "側邊欄",
  "cfg.f.sisyphus": "Sisyphus",
  "cfg.f.sisyphusAgent": "Sisyphus 代理",
  "cfg.f.skill": "技能",
  "cfg.f.skills": "技能",
  "cfg.f.smallModel": "小型模型",
  "cfg.f.snapshot": "快照",
  "cfg.f.soul": "靈魂",
  "cfg.f.sourceUrl": "來源 URL",
  "cfg.f.sources": "來源",
  "cfg.f.staleTimeoutMs": "陳舊逾時（毫秒）",
  "cfg.f.startWork": "開始工作",
  "cfg.f.stateDir": "狀態目錄",
  "cfg.f.status": "狀態",
  "cfg.f.stepCount": "步驟數",
  "cfg.f.steps": "步驟數",
  "cfg.f.storagePath": "儲存路徑",
  "cfg.f.strategies": "策略",
  "cfg.f.subagentDepth": "子代理深度",
  "cfg.f.subagentType": "子代理類型",
  "cfg.f.subscriberRing": "訂閱者環形大小",
  "cfg.f.subscriptions": "訂閱",
  "cfg.f.subtask": "子工作",
  "cfg.f.supersedeWrites": "覆蓋寫入",
  "cfg.f.sync": "同步",
  "cfg.f.syncPollTimeoutMs": "同步輪詢逾時（毫秒）",
  "cfg.f.tailTurns": "保留尾端回合數",
  "cfg.f.task": "工作",
  "cfg.f.taskCleanupDelayMs": "工作清理延遲（毫秒）",
  "cfg.f.taskListId": "工作清單 ID",
  "cfg.f.tasks": "工作",
  "cfg.f.taskSystem": "工作系統",
  "cfg.f.taskTtlMs": "工作存留時間（毫秒）",
  "cfg.f.tdd": "TDD",
  "cfg.f.team": "團隊",
  "cfg.f.teamAllowedPaths": "團隊允許路徑",
  "cfg.f.teamMode": "團隊模式",
  "cfg.f.telegramBotToken": "Telegram 機器人權杖",
  "cfg.f.telegramChatId": "Telegram 聊天 ID",
  "cfg.f.telemetry": "遙測",
  "cfg.f.temperature": "溫度",
  "cfg.f.template": "範本",
  "cfg.f.textVerbosity": "文字詳細度",
  "cfg.f.thinking": "思考",
  "cfg.f.timeout": "逾時（毫秒）",
  "cfg.f.timeoutMinutes": "逾時（分鐘）",
  "cfg.f.timeoutMs": "逾時（毫秒）",
  "cfg.f.timeoutSeconds": "逾時（秒）",
  "cfg.f.tmux": "tmux",
  "cfg.f.tmuxVisualization": "tmux 視覺化",
  "cfg.f.todowrite": "TodoWrite",
  "cfg.f.toolCall": "工具呼叫",
  "cfg.f.toolExposure": "工具公開方式",
  "cfg.f.toolOutput": "工具輸出",
  "cfg.f.tools": "工具",
  "cfg.f.topP": "Top-p",
  "cfg.f.trigger": "觸發條件",
  "cfg.f.truncateAllToolOutputs": "截斷所有工具輸出",
  "cfg.f.ttlMs": "存留時間（毫秒）",
  "cfg.f.tui": "TUI",
  "cfg.f.turnProtection": "回合保護",
  "cfg.f.turns": "回合數",
  "cfg.f.type": "類型",
  "cfg.f.ultrawork": "Ultrawork",
  "cfg.f.unavailableCategories": "不可用類別警告",
  "cfg.f.url": "URL",
  "cfg.f.urls": "URL",
  "cfg.f.username": "使用者名稱",
  "cfg.f.variant": "變體",
  "cfg.f.variants": "變體",
  "cfg.f.version": "版本",
  "cfg.f.wait": "等待",
  "cfg.f.warnings": "警告",
  "cfg.f.warnUnavailable": "不可用時警告",
  "cfg.f.watchDebounceMs": "監看去抖動（毫秒）",
  "cfg.f.watcher": "監看器",
  "cfg.f.webfetch": "WebFetch",
  "cfg.f.websearch": "WebSearch",
  "cfg.f.whitelist": "白名單",
  "cfg.f.worktreePath": "Worktree 路徑",
  "cfg.f.writeNotice": "寫入提示",
};

const enFallback: Readonly<Record<string, string>> = en;

/**
 * The single translation entry point used by the webview `t()` binding:
 * injected table hit -> English table hit -> the id itself. Never throws and
 * never returns a blank string, so a drifting wire payload degrades to
 * readable English (or a debuggable id) instead of crashing the UI.
 */
export function translateWithFallback(
  table: Readonly<Record<string, string>>,
  id: string,
): string {
  return table[id] ?? enFallback[id] ?? id;
}
